version: "2.0"
services:
  elasticsearch:
    container_name: elasticsearch_cd
    image: chartdeskes:cn
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - docker_elk
    ulimits:
      nofile:
         soft: 65536
         hard: 65536
    volumes:
      - esdata:/usr/share/elasticsearch/data
  kibana:
    container_name: kibana_2
    image: docker.elastic.co/kibana/kibana:7.10.1
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    networks:
      - docker_elk
    depends_on:
      - elasticsearch

networks:
  docker_elk:
    driver: bridge

volumes:
  esdata: