---
version: '3.3'
services:
  # https://github.com/elastic/stack-docker/blob/master/docker-compose.yml
  elasticsearch:
    image: nexushubs/elasticsearch-cn:6.4.2
    container_name: elasticsearch
    ports:
      - '9200:9200'
    volumes:
      - 'es_data:/usr/share/elasticsearch/data'
      - './config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml'
      - './config/analysis-ik/IKAnalyzer.cfg.xml:/usr/share/elasticsearch/config/analysis-ik/IKAnalyzer.cfg.xml'
      - './config/analysis-ik/custom:/usr/share/elasticsearch/config/analysis-ik/custom'
    healthcheck:
      test: curl https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
volumes:
  es_data:
